import type { Agent, InvestmentOpportunity, Property } from "@/types/property";

export const agents: Agent[] = [
  {
    slug: "shirin-moradi",
    name_fa: "شیرین مرادی",
    name_en: "Shirin Moradi",
    title_fa: "مشاور ارشد املاک لوکس",
    title_en: "Senior Luxury Property Consultant",
    bio_fa: "بیش از ۱۲ سال تجربه در معاملات املاک لوکس تهران و شمال کشور.",
    bio_en: "12+ years advising on luxury property transactions in Tehran and northern Iran.",
    photo: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?q=80&w=400&auto=format&fit=crop",
    phone: "+98 21 0000 0000",
    whatsapp: "+98 900 000 0000",
  },
  {
    slug: "kaveh-ahmadi",
    name_fa: "کاوه احمدی",
    name_en: "Kaveh Ahmadi",
    title_fa: "مشاور سرمایه‌گذاری ملکی",
    title_en: "Real Estate Investment Advisor",
    bio_fa: "تمرکز بر فرصت‌های سرمایه‌گذاری و همکاری با سازندگان پروژه‌های لوکس.",
    bio_en: "Focused on investment opportunities and partnerships with luxury developers.",
    photo: "https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=400&auto=format&fit=crop",
    phone: "+98 21 0000 0001",
    whatsapp: "+98 900 000 0001",
  },
  {
    slug: "nazanin-hosseini",
    name_fa: "نازنین حسینی",
    name_en: "Nazanin Hosseini",
    title_fa: "مشاور املاک بین‌المللی",
    title_en: "International Client Consultant",
    bio_fa: "همراه سرمایه‌گذاران خارجی در تمام مراحل خرید، از بازدید تا قرارداد.",
    bio_en: "Guides international investors from first viewing through to contract.",
    photo: "https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=400&auto=format&fit=crop",
    phone: "+98 21 0000 0002",
    whatsapp: "+98 900 000 0002",
  },
];

export const properties: Property[] = [
  {
    slug: "villa-zafaranieh-118",
    title_fa: "ویلای معماری زعفرانیه",
    title_en: "Zafaranieh Architectural Villa",
    type: "villa",
    location_fa: "زعفرانیه، تهران",
    location_en: "Zafaranieh, Tehran",
    price: 285_000_000_000,
    areaSqm: 620,
    bedrooms: 5,
    parkingSpaces: 4,
    floor: 0,
    yearBuilt: 2022,
    amenities_fa: ["استخر سرپوشیده", "سونا و جکوزی", "هوشمندسازی کامل", "باغ اختصاصی"],
    amenities_en: ["Indoor pool", "Sauna & jacuzzi", "Full home automation", "Private garden"],
    documentStatus_fa: "تک‌برگ، سند قطعی",
    documentStatus_en: "Clean single-deed title",
    projectStatus: "ready",
    purposeFit: "both",
    featured: true,
    architecturalNotes_fa: "طراحی معماری توسط استودیوی داخلی، نمای سنگ و چوب طبیعی.",
    architecturalNotes_en: "In-house architectural design; natural stone and timber façade.",
    description_fa:
      "ویلایی خاص در قلب زعفرانیه با معماری معاصر، نورگیری وسیع و چیدمانی که آسایش خانواده را با حس یک اثر معماری ترکیب می‌کند. مناسب سکونت و حفظ ارزش سرمایه در بلندمدت.",
    description_en:
      "A distinctive contemporary villa in the heart of Zafaranieh, with generous natural light and a layout built for family life as much as architectural presence. Suited to both residence and long-term value.",
    images: [
      "https://images.unsplash.com/photo-1613977257363-707ba9348227?q=80&w=1600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=1600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1600&auto=format&fit=crop",
    ],
    agentSlug: "shirin-moradi",
    lat: 35.8083,
    lng: 51.4262,
  },
  {
    slug: "penthouse-elahieh-sky",
    title_fa: "پنت‌هاوس الهیه",
    title_en: "Elahieh Sky Penthouse",
    type: "penthouse",
    location_fa: "الهیه، تهران",
    location_en: "Elahieh, Tehran",
    price: 410_000_000_000,
    areaSqm: 480,
    bedrooms: 4,
    parkingSpaces: 3,
    floor: 18,
    yearBuilt: 2023,
    amenities_fa: ["روف‌گاردن اختصاصی", "ویو کامل شهر", "آسانسور اختصاصی", "استخر روف‌تاپ مشترک"],
    amenities_en: ["Private roof garden", "Full city view", "Private elevator", "Shared rooftop pool"],
    documentStatus_fa: "تک‌برگ",
    documentStatus_en: "Single-deed title",
    projectStatus: "ready",
    purposeFit: "investment",
    featured: true,
    description_fa:
      "پنت‌هاوسی در بالاترین طبقه یکی از برج‌های منتخب الهیه، با ویوی بی‌مانند به شهر و فضایی برای زندگی و میزبانی در سطح بین‌المللی.",
    description_en:
      "A top-floor penthouse in one of Elahieh's most select towers, with an uninterrupted city view and a layout built for international-standard living and hosting.",
    images: [
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=1600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?q=80&w=1600&auto=format&fit=crop",
    ],
    agentSlug: "kaveh-ahmadi",
    lat: 35.8062,
    lng: 51.4231,
  },
  {
    slug: "tower-kamranieh-residence",
    title_fa: "واحد لوکس برج کامرانیه",
    title_en: "Kamranieh Tower Residence",
    type: "tower",
    location_fa: "کامرانیه، تهران",
    location_en: "Kamranieh, Tehran",
    price: 190_000_000_000,
    areaSqm: 310,
    bedrooms: 3,
    parkingSpaces: 2,
    floor: 11,
    yearBuilt: 2021,
    amenities_fa: ["لابی هتلی", "سالن بدنسازی خصوصی", "امنیت ۲۴ ساعته"],
    amenities_en: ["Hotel-style lobby", "Private gym", "24-hour security"],
    documentStatus_fa: "تک‌برگ",
    documentStatus_en: "Single-deed title",
    projectStatus: "ready",
    purposeFit: "residence",
    featured: false,
    description_fa:
      "واحدی آفتاب‌گیر در یکی از برج‌های معتبر کامرانیه، با چیدمانی کاربردی برای زندگی خانوادگی در سطح بالا.",
    description_en:
      "A bright, well-proportioned unit in one of Kamranieh's established towers, laid out for high-end family living.",
    images: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1600&auto=format&fit=crop",
    ],
    agentSlug: "shirin-moradi",
  },
  {
    slug: "villa-niavaran-heritage",
    title_fa: "ویلای کلکسیونی نیاوران",
    title_en: "Niavaran Collector's Villa",
    type: "villa",
    location_fa: "نیاوران، تهران",
    location_en: "Niavaran, Tehran",
    price: 0,
    priceOnRequest: true,
    areaSqm: 900,
    bedrooms: 6,
    parkingSpaces: 6,
    yearBuilt: 2019,
    amenities_fa: ["باغ قدیمی با درختان کهن", "استخر روباز", "سالن پذیرایی مجزا"],
    amenities_en: ["Mature heritage garden", "Outdoor pool", "Separate reception hall"],
    documentStatus_fa: "تک‌برگ، سند قطعی",
    documentStatus_en: "Clean single-deed title",
    projectStatus: "ready",
    purposeFit: "both",
    featured: true,
    architecturalNotes_fa: "یکی از ملک‌های کلکسیونی و کمیاب منطقه نیاوران با باغی چند دهه‌ای.",
    architecturalNotes_en: "A rare, collector-grade property in Niavaran with a decades-old garden.",
    description_fa:
      "ملکی خاص و کمیاب که به‌ندرت به بازار عرضه می‌شود؛ ترکیبی از باغ قدیمی، فضای سکونت و ارزش سرمایه‌گذاری بلندمدت.",
    description_en:
      "A rare property that seldom reaches the market — a heritage garden, generous living space, and long-term investment value in one address.",
    images: [
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?q=80&w=1600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?q=80&w=1600&auto=format&fit=crop",
    ],
    agentSlug: "nazanin-hosseini",
  },
  {
    slug: "apartment-farmanieh-view",
    title_fa: "آپارتمان لوکس فرمانیه",
    title_en: "Farmanieh View Apartment",
    type: "apartment",
    location_fa: "فرمانیه، تهران",
    location_en: "Farmanieh, Tehran",
    price: 140_000_000_000,
    areaSqm: 240,
    bedrooms: 3,
    parkingSpaces: 2,
    floor: 6,
    yearBuilt: 2020,
    amenities_fa: ["ویو کوه", "لابی مجهز", "انباری اختصاصی"],
    amenities_en: ["Mountain view", "Furnished lobby", "Private storage"],
    documentStatus_fa: "تک‌برگ",
    documentStatus_en: "Single-deed title",
    projectStatus: "ready",
    purposeFit: "residence",
    featured: false,
    description_fa: "آپارتمانی مناسب سکونت با نور مطلوب و ویویی رو به رشته‌کوه البرز.",
    description_en: "A residence-ready apartment with excellent light and a clear view of the Alborz range.",
    images: [
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?q=80&w=1600&auto=format&fit=crop",
    ],
    agentSlug: "kaveh-ahmadi",
  },
  {
    slug: "complex-lavasan-collection",
    title_fa: "مجتمع مسکونی لوکس لواسان",
    title_en: "Lavasan Luxury Residence Collection",
    type: "residential-complex",
    location_fa: "لواسان، تهران",
    location_en: "Lavasan, Tehran",
    price: 320_000_000_000,
    areaSqm: 540,
    bedrooms: 5,
    parkingSpaces: 3,
    yearBuilt: 2025,
    amenities_fa: ["استخر مشترک", "زمین بازی کودکان", "فضای سبز مرکزی"],
    amenities_en: ["Shared pool", "Children's play area", "Central green space"],
    documentStatus_fa: "در حال اخذ سند",
    documentStatus_en: "Title in process",
    projectStatus: "under-construction",
    purposeFit: "investment",
    featured: true,
    description_fa:
      "پروژه‌ای در حال ساخت در لواسان با رویکرد سرمایه‌گذاری زودهنگام؛ یکی از فرصت‌های ویژه بام ایران.",
    description_en:
      "An under-construction project in Lavasan, positioned as an early-entry investment — one of Bam Iran's selected opportunities.",
    images: [
      "https://images.unsplash.com/photo-1600566752355-35792bedcfea?q=80&w=1600&auto=format&fit=crop",
    ],
    agentSlug: "nazanin-hosseini",
  },
];

export const investmentOpportunities: InvestmentOpportunity[] = [
  {
    slug: "lavasan-early-entry",
    title_fa: "ورود زودهنگام به مجموعه لواسان",
    title_en: "Early Entry — Lavasan Collection",
    summary_fa: "فرصت سرمایه‌گذاری در فاز اول ساخت، پیش از عرضه عمومی.",
    summary_en: "An investment opportunity in the first construction phase, ahead of public release.",
    tag_fa: "فرصت ویژه",
    tag_en: "Private Opportunity",
    relatedPropertySlug: "complex-lavasan-collection",
    image: "https://images.unsplash.com/photo-1600566752355-35792bedcfea?q=80&w=1200&auto=format&fit=crop",
  },
  {
    slug: "niavaran-collectors-pick",
    title_fa: "منتخب بام ایران: نیاوران",
    title_en: "Bam Iran Selection — Niavaran",
    summary_fa: "ملکی کمیاب که به‌ندرت در بازار املاک لوکس تهران عرضه می‌شود.",
    summary_en: "A rare address that seldom appears on Tehran's luxury market.",
    tag_fa: "منتخب بام ایران",
    tag_en: "Bam Iran Selection",
    relatedPropertySlug: "villa-niavaran-heritage",
    image: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?q=80&w=1200&auto=format&fit=crop",
  },
];

export function getPropertyBySlug(slug: string) {
  return properties.find((p) => p.slug === slug);
}

export function getAgentBySlug(slug: string) {
  return agents.find((a) => a.slug === slug);
}

export function getSimilarProperties(property: Property, limit = 3) {
  return properties
    .filter((p) => p.slug !== property.slug && p.type === property.type)
    .slice(0, limit);
}
